import { clientsClaim } from "workbox-core";
import {
  cleanupOutdatedCaches,
  precacheAndRoute,
} from "workbox-precaching";

self.skipWaiting();
clientsClaim();

cleanupOutdatedCaches();

/*
 * VitePWA replaces self.__WB_MANIFEST
 * with the files generated by the build.
 */
precacheAndRoute(self.__WB_MANIFEST);

/*
 * Receive Web Push messages.
 */
self.addEventListener(
  "push",
  (event) => {
    let data = {};

    if (event.data) {
      try {
        data = event.data.json();
      } catch {
        data = {
          body: event.data.text(),
        };
      }
    }

    const title =
      data.title || "Club100";

    const options = {
      body:
        data.body ||
        "You have a new Club100 notification.",

      icon:
        data.icon ||
        "/icons/icon-192.png",

      badge:
        data.badge ||
        "/icons/icon-192.png",

      data: {
        url:
          data.url ||
          "/dashboard",

        ...(data.data || {}),
      },
    };

    event.waitUntil(
      self.registration.showNotification(
        title,
        options
      )
    );
  }
);


/*
 * Handle notification click.
 *
 * If Club100 is already open, focus the
 * existing window and navigate to the URL.
 * Otherwise open a new window.
 */
self.addEventListener(
  "notificationclick",
  (event) => {
    event.notification.close();

    const targetUrl =
      event.notification.data?.url ||
      "/dashboard";

    event.waitUntil(
      self.clients
        .matchAll({
          type: "window",
          includeUncontrolled: true,
        })
        .then(
          async (clientList) => {
            for (const client of clientList) {
              if ("focus" in client) {
                await client.focus();

                if ("navigate" in client) {
                  await client.navigate(
                    targetUrl
                  );
                }

                return;
              }
            }

            if (
              self.clients.openWindow
            ) {
              return self.clients.openWindow(
                targetUrl
              );
            }
          }
        )
    );
  }
);